name: Use Composite Action from Another Repo

on:
  push:
    branches:
      - main

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use greeting composite actions
        uses: shaik-byte/greeting-actions/.github/workflows/greetings@main

        
        
