name: Use Composite Action from Another Repo

on:
  push:
    branches:
      - "**"

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use greeting composite actions
        uses: shaik-byte/greeting-actions/.github/actions/greetings@main
        
        
